### ISSUE TITLE
move to using Hugo generator

### ISSUE THREAD

**Issue by privatemaker** [tracking-exposed/tracking.exposed#3]
Recently decided to use [Hugo](https://gohugo.io) for all the public facing websites. This will be completed before work on #1 is done. All work will be pushed to [hugo-refactor](https://github.com/tracking-exposed/tracking.exposed/tree/hugo-refactor) branch for now.

**Comment by vecna** [comment]
This branch has been updated by using hugo-theme-trex at the branch 'new-default-site' and this is the linked PR https://github.com/tracking-exposed/hugo-theme-trex/pull/14
